import PDFDocument from "pdfkit";


export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc =new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "CortexAI",
        Title: data.title,
        Creater: "CortexAI",
      },
    });

    const chunks = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", () => reject);
    // title
    doc
      .fontSize(28)
      .text(data.title, {
        align: "center",
      })
      .fillColor("#111827");

    if (data.subtitle) {
      doc.moveDown(0.5);
    }
    //   subtitle
    doc
      .fontSize(20)
      .text(data.subtitle, {
        align: "center",
      })
      .fillColor("#6B7280");

    doc.moveDown(2);

    // section

    data?.section?.forEach((s) => {
      doc.fontSize(18).text(s.heading).fillColor("#111827");

      doc.moveDown(0.5);
      s?.points?.forEach((p) => {
        doc
          .fontSize(14)
          .text("• " + p, {
            indent: 10,
            lineGap: 5,
          })
          .fillColor("#374151");
      });

      doc.moveDown();
    });

    doc.moveDown();
    // footer
    doc
      .fontSize(12)
      .text("Generated By CotaxAi", {
        align: "center",
      })
      .fillColor("#9CA3AF");

    doc.end();
  });
};
