import { Colors } from "./colors.js";

export const addFooter = (doc) => {
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;

  doc
    .save()
    .moveTo(50, pageHeight - 55)
    .lineTo(pageWidth - 50, pageHeight - 55)
    .lineWidth(0.7)
    .strokeColor(Colors.border)
    .stroke()
    .restore();

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(Colors.muted)
    .text(
      "Generated by CortexAI",
      50,
      pageHeight - 42,
      {
        width: 200,
        lineBreak: false,
      }
    );

  doc.text(
    `Page ${doc.page.number}`,
    pageWidth - 100,
    pageHeight - 42,
    {
      width: 50,
      align: "right",
      lineBreak: false,
    }
  );
};
