import { Colors } from "./color.js";

export const addContentSlide = (
  ppt,
  title,
  points = [],
  page,
  total
) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: Colors.light,
  };

  // Brand
  slide.addText("CORTEXAI", {
    x: 0.65,
    y: 0.35,
    w: 1.5,
    h: 0.2,
    color: Colors.primary,
    fontSize: 9,
    bold: true,
    charSpacing: 1.5,
    margin: 0,
  });

  // Page number
  slide.addText(`${String(page).padStart(2, "0")}`, {
    x: 12.1,
    y: 0.3,
    w: 0.6,
    h: 0.3,
    color: Colors.primary,
    fontSize: 11,
    bold: true,
    align: "right",
    margin: 0,
  });

  // Title
  slide.addText(title || "Untitled", {
    x: 0.65,
    y: 0.85,
    w: 10.5,
    h: 0.55,
    color: Colors.secondary,
    bold: true,
    fontSize: 27,
    fit: "shrink",
    margin: 0,
  });

  // Header line
  slide.addShape(ppt.ShapeType.line, {
    x: 0.65,
    y: 1.55,
    w: 1.15,
    h: 0,
    line: {
      color: Colors.primary,
      width: 3,
    },
  });

  slide.addShape(ppt.ShapeType.line, {
    x: 1.8,
    y: 1.55,
    w: 10.85,
    h: 0,
    line: {
      color: Colors.border,
      width: 1,
    },
  });

  const visiblePoints = points.slice(0, 6);

  visiblePoints.forEach((point, i) => {
    const row = Math.floor(i / 2);
    const column = i % 2;

    const x = column === 0 ? 0.65 : 6.55;
    const y = 1.95 + row * 1.35;

    // Card
    slide.addShape(ppt.ShapeType.roundRect, {
      x,
      y,
      w: 5.7,
      h: 1.05,
      fill: {
        color: Colors.card,
      },
      line: {
        color: Colors.border,
        width: 1,
      },
      shadow: {
        type: "outer",
        color: "94A3B8",
        blur: 1,
        angle: 45,
        distance: 1,
        opacity: 0.12,
      },
    });

    // Number badge
    const badgeColor =
      i % 3 === 0
        ? Colors.primary
        : i % 3 === 1
        ? Colors.accent
        : Colors.cyan;

    slide.addShape(ppt.ShapeType.ellipse, {
      x: x + 0.22,
      y: y + 0.28,
      w: 0.48,
      h: 0.48,
      fill: {
        color: badgeColor,
      },
      line: {
        color: Colors.white,
        transparency: 100,
      },
    });

    slide.addText(`${i + 1}`, {
      x: x + 0.22,
      y: y + 0.39,
      w: 0.48,
      h: 0.15,
      align: "center",
      color: Colors.white,
      fontSize: 10,
      bold: true,
      margin: 0,
    });

    // Point
    slide.addText(point, {
      x: x + 0.9,
      y: y + 0.22,
      w: 4.45,
      h: 0.6,
      color: Colors.text,
      fontSize: 14,
      fit: "shrink",
      valign: "mid",
      margin: 0,
    });
  });

  // Progress background
  slide.addShape(ppt.ShapeType.roundRect, {
    x: 4.1,
    y: 6.65,
    w: 5.1,
    h: 0.08,
    fill: {
      color: Colors.border,
    },
    line: {
      color: Colors.border,
      transparency: 100,
    },
  });

  // Progress
  const progressWidth = 5.1 * (page / total);

  slide.addShape(ppt.ShapeType.roundRect, {
    x: 4.1,
    y: 6.65,
    w: progressWidth,
    h: 0.08,
    fill: {
      color: Colors.primary,
    },
    line: {
      color: Colors.primary,
      transparency: 100,
    },
  });

  // Footer
  slide.addText("Generated by CortexAI", {
    x: 0.65,
    y: 6.48,
    w: 2.5,
    h: 0.25,
    color: Colors.muted,
    fontSize: 9,
    margin: 0,
  });

  slide.addText(`${page} / ${total}`, {
    x: 11.7,
    y: 6.48,
    w: 0.9,
    h: 0.25,
    color: Colors.muted,
    fontSize: 9,
    bold: true,
    align: "right",
    margin: 0,
  });
};