import { Colors } from "./color.js";


export const addCover = (ppt, data) => {
  const slide = ppt.addSlide();

  slide.background = {
    color: Colors.secondary,
  };

  // Decorative shape
 

  // Top accent
  slide.addShape(ppt.ShapeType.rect, {
    x: 0,
    y: 0,
    w: 13.33,
    h: 0.12,
    fill: {
      color: Colors.primary,
    },
    line: {
      color: Colors.primary,
    },
  });

  // Brand badge
  slide.addShape(ppt.ShapeType.roundRect, {
    x: 0.75,
    y: 0.7,
    w: 2.1,
    h: 0.45,
    fill: {
      color: Colors.primary,
      transparency: 10,
    },
    line: {
      color: Colors.primary,
      transparency: 100,
    },
  });

  slide.addText("✦ CORTEXAI", {
    x: 0.85,
    y: 0.79,
    w: 1.9,
    h: 0.2,
    color: Colors.white,
    fontSize: 11,
    bold: true,
    align: "center",
    margin: 0,
  });

  // Title
  slide.addText(data.title || "Untitled Presentation", {
    x: 0.75,
    y: 2,
    w: 9.5,
    h: 1.2,
    color: Colors.white,
    bold: true,
    fontSize: 38,
    fit: "shrink",
    margin: 0,
  });

  // Accent line
  slide.addShape(ppt.ShapeType.line, {
    x: 0.78,
    y: 3.35,
    w: 1.3,
    h: 0,
    line: {
      color: Colors.cyan,
      width: 4,
    },
  });

  // Subtitle
  slide.addText(
    data.subtitle || "A modern presentation generated by CortexAI",
    {
      x: 0.78,
      y: 3.65,
      w: 8.7,
      h: 0.65,
      color: "CBD5E1",
      fontSize: 17,
      fit: "shrink",
      margin: 0,
    }
  );

  // Footer
  slide.addText("AI GENERATED PRESENTATION", {
    x: 0.78,
    y: 6.55,
    w: 3,
    h: 0.2,
    color: "94A3B8",
    fontSize: 9,
    bold: true,
    charSpacing: 1.5,
    margin: 0,
  });

  slide.addText("CortexAI", {
    x: 11.1,
    y: 6.55,
    w: 1.5,
    h: 0.2,
    color: Colors.white,
    fontSize: 10,
    bold: true,
    align: "right",
    margin: 0,
  });
};